### ISSUE TITLE
Encoding / special characters

### ISSUE THREAD

**Issue by wagenpfeil** [KN4CK3R/KeePassBrowserImporter#10]
It seems that there are encoding issues when importing special characters. For instance the german Amazon page has the title

> Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr

but after import it is displayed as

> Amazon.de: GÃ¼nstige Preise fÃ¼r Elektronik & Foto, Filme, Musik, BÃ¼cher, Games, Spielzeug & mehr

This is exactly the ANSI representation of the correct UTF-8 without BOM on a german Windows 7 x64, so it appears there is some problem with the character encoding during import.

It is only a minor issue, otherwise **it's really a great plugin** and has saved me a lot of time.

Thank you very much!

**Comment by KN4CK3R** [comment]
Das ist der Titel, den das Plugin für den Eintrag von der Webseite ausliest oder? Ich schau mir an, warum das nicht passt.

**Comment by wagenpfeil** [comment]
Ja, ganz genau. Super, dass du so schnell reagierst :-)

**Comment by KN4CK3R** [comment]
Die .NET Funktion zum Runterladen der Seite verlangt vom Entwickler schon im Voraus zu wissen, welches Encoding ihn erwartet. Das ist Quatsch, weil man das nicht wissen kann im Normalfall. Die neue Version schaut jetzt in der Antwort vom Server nach dem verwendeten Encoding und benutzt das dann.

**Comment by wagenpfeil** [comment]
Top, werde das sobald ich dazu komme testen.
