### ISSUE TITLE
Portable Firefox

### ISSUE THREAD

**Issue by MichelePezza** [KN4CK3R/KeePassBrowserImporter#3]
It will be appreciated if you add a functionality to input manually the profiles path for Firefox.... the automatic detection in %APPDATA% doesn't allow to use your plugin with a portables version of Firefox.
Thanks. MP

**Comment by KN4CK3R** [comment]
I added support for custom paths in v1.0.1. Have fun :)

**Comment by MichelePezza** [comment]
I use only a portable version of Firefox.
It doesn't able to insert a custom profile folder if firefox isn't installed on the pc (I cannot select the checkbox to choose Firefox Browser). Thanks for your job.
MP

**Comment by KN4CK3R** [comment]
Second try, see v1.0.1.1
https://github.com/KN4CK3R/KeePassBrowserImporter/releases/tag/v1.0.1.1

**Comment by MichelePezza** [comment]
Unsuccessfull try :-(
I got an error dialog as I open the plugin

Here the details:
System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\UserZYZ\AppData\Roaming\Mozilla\Firefox\Profiles'.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileSystemEnumerableIterator`1.CommonInit()
   in System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   in System.IO.Directory.EnumerateDirectories(String path)
   in KeePassBrowserImporter.Firefox.GetProfiles()
   in KeePassBrowserImporter.ProviderForm.SelectBrowser_CheckedChanged(Object sender, EventArgs e)
   in System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   in System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   in System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   in System.Windows.Forms.RadioButton.OnEnter(EventArgs e)
   in System.Windows.Forms.ContainerControl.UpdateFocusedControl()

Thx 
MP
