### ISSUE TITLE
Win/HEDO virus warning (AVG Free)

### ISSUE THREAD

**Issue by ruudsieb** [KN4CK3R/KeePassBrowserImporter#4]
Just downloaded the plugin plgx (181d870), and copied it to the plugins directory. When starting KeePass, AVG immediately complains about the virus, and KeePass generates an error obviously because it can't access the KeePassBrowserImporter.dll temp file.
My virus definitions are up to date according AVG

**Comment by KN4CK3R** [comment]
Which file does it complain about?
I'm not really surprised an AV does complain about the functionality because every login stealer would work like this and use the files which are shipped with the plugin.

**Comment by KN4CK3R** [comment]
Here are virustotal scans of the main files:

KeePassBrowserImporter.dll (compiled with .NET4 and KeePass 2.44)
https://virustotal.com/de/file/00e27aff9d252362dfc2a2a45cb7c96b81f1795000b3c38e518c2ba06e778d59/analysis/
htmlagilitypack.dll
https://virustotal.com/de/file/6fd971f30d36ad09523dcde9c5008dd1331736b4207a1e9fe672d209991587e1/analysis/
system.data.sqlite.dll
https://virustotal.com/de/file/3c7a9267f520208bad23fa5de9508d42f0688869616346d6393414917b1886a7/analysis/

All have 0 positives.

**Comment by ruudsieb** [comment]
It complained about KeePassBrowserImporter.dll in the temp directory. I
uploaded the dll to virustotal.com and got the same results as you. So most
likely a false positive, nevertheless annoying. I reported the file back to
AVG.

Note that this prevents me from using the plugin, unless i disable AVG.
Op 14 jun. 2016 21:11 schreef "KN4CK3R" <notifications@github.com>:
