### ISSUE TITLE
KeePassBrowserImporter 1.0.1.1 and Portable Firefox

### ISSUE THREAD

**Issue by MichelePezza** [KN4CK3R/KeePassBrowserImporter#6]
Unsuccessfull try :-(
I got an error dialog as I open the plugin

Here the details:
System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\UserZYZ\AppData\Roaming\Mozilla\Firefox\Profiles'.
in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
in System.IO.FileSystemEnumerableIterator1.CommonInit() in System.IO.FileSystemEnumerableIterator1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
in System.IO.Directory.EnumerateDirectories(String path)
in KeePassBrowserImporter.Firefox.GetProfiles()
in KeePassBrowserImporter.ProviderForm.SelectBrowser_CheckedChanged(Object sender, EventArgs e)
in System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
in System.Windows.Forms.RadioButton.set_Checked(Boolean value)
in System.Windows.Forms.RadioButton.OnClick(EventArgs e)
in System.Windows.Forms.RadioButton.OnEnter(EventArgs e)
in System.Windows.Forms.ContainerControl.UpdateFocusedControl()

Thx
MP

**Comment by KN4CK3R** [comment]
fixed @ v1.0.2
