### ISSUE TITLE
Plugin cannot import time records from Firefox (password created, password last used/modified)

### ISSUE THREAD

**Issue by L0ginErr0r** [KN4CK3R/KeePassBrowserImporter#7]
Would it be possible for the plugin to take both available in Firefox dates and transfer them to KeePass?
I know KeePass has two columns:
_Creation Time
Last Modification Time_
After importing all passwords they are both set at the time of the import. 
However, this information is stored in Firefox under:
_First time used
Last Change_ 

Would it be possible to import all those dates together with the passwords?

**Comment by KN4CK3R** [comment]
added @ v1.0.2
