### ISSUE TITLE
Doesn't allow to import from portable versions of Opera and Chromium

### ISSUE THREAD

**Issue by S-ed** [KN4CK3R/KeePassBrowserImporter#9]
Under browser selection Opera and Chromium are inactive if they are not installed on the system.

It would be useful to have same ability as for Firefox and Chrome.

**Comment by KN4CK3R** [comment]
I have added more portable browsers in v1.0.3.
But I don't know why you would use other browsers than Firefox in a portable way. They encrypt the credentials with informations of the current windows users. You can't decrypt these on an other system.
